### ISSUE TITLE
mauvile roulette

### ISSUE THREAD

**Issue by jplogan** [resetes12/pokeemerald#3]
playing on mgba on the linux version using aa chromebook.  i try to play roulette at the gamecorner and the ball just seems to slowly work its way off screen when i spin and it never stops.  any ideas why?

**Comment by resetes12** [comment]
Hey! I need more information because I cannot reproduce this issue. I have tried in both mGBA and real hardware. Is it a one-thing issue, or does it happen every time you try? 

Have you tried updating mGBA, if possible? If not, then it's probably a specific mGBA linux issue (although I'm not sure, but this kind of bugs are usually emulator doing).

**Comment by SDarkra1** [comment]
I have tried recreating the issue, but haven't been able to. What version of Debian is your Crostini using?

**Comment by resetes12** [comment]
> I have tried recreating the issue, but haven't been able to. What version of Debian is your Crostini using? Do you have any beta flags enabled? What version of mGBA are you using?
> 
> > Have you tried updating mGBA, if possible? If not, then it's probably a specific mGBA linux issue (although I'm not sure, but this kind of bugs are usually emulator doing).
> 
> It could be caused by Crostini (ChromeOS Linux functionality), I have run into timing issues when using it before. We don't know if they're using it or have flashed some distro onto the drive, but Crostini seems most likely.

Then there's little to do on my part. Thanks for letting me know though.
