### ISSUE TITLE
"[ERROR] GBA Savedata: Savegame time offset set to 0"

### ISSUE THREAD

**Issue by byougaichuu** [resetes12/pokeemerald#34]
Hello!
Huge fan of this RomHack, I have been having a blast with it for a few weeks now. I've run into a peculiar issue for which I did not find much online precedent and wanted to know if the problem was accounted for.

The romhack allows the player to change the time of the day using the clock in Littleroot Town, even if RTC is selected at the beginning of the save, which I did. I changed the time to early in the morning to evolve my Kirlia and then set it back to the time it was supposed to be originally. I now get the following error on startup with mGBA.

<img width="195" alt="Error" src="https://github.com/resetes12/pokeemerald/assets/171370497/a444bca2-e210-4d65-b00c-b72426bcc99d">

In-game, the day-night cycle still occurs according to system time, but any time-ticking-related event has stopped happening - no more berry growth. I have tried a lot of potential fixes but without much success.

I doubt my save is salvageable at this point, but I'm curious as to what might have happened. I have not yet tried to see if the issue could be reproduced consistently.

**Comment by resetes12** [comment]
"The game resets the date to 1/1/2000 when you start or reset the clock. As the game uses this date to track daily events and berry growth, timed events will not happen again until you get to "your previous date before resetting the clock".

Example: It's your 15th day in-game (counted by the RTC, so 15 real-life days). You change the clock so the date resets to day 1. You need to wait until day 16 to get time events again.

In order to fix it, 1.3.5.2 introduced a (maybe temporal?) fix. First, enable the DEBUG menu. Then, go to the wallclock in your house and hold SELECT and then press the L Button. You will hear a sound. This sound means that the in-game clock has been advanced by 10 days. Press the button combination as many times as you think you need and in-game timed events will work again. You will need to do this every time you change the clock if you want time-events again. So, if you reset your clock on day 23, you will need to press the combination 3 times."

**Comment by byougaichuu** [comment]
Thank you very much for taking the time to answer me, and my apologies for reporting a problem that was already accounted for. Could you tell me which piece of documentation this is from so that I do not do the same mistake again, please?

I have tried this fix and it indeed made time pass as advertised. However, even after pressing it a bunch of times I still get the same emulator error on startup. When you wrote that the fix was "maybe temporal", did you mean temporary?

**Comment by byougaichuu** [comment]
Understood! Thanks for the precision, I understand that it's not worth investing time into, given that not many people do this. I have messed a lot with my save file trying to fix it before, so you're right in saying that the most likely option is that my file got corrupted in a way or another. I will give it a try with another emulator sometime, but yeah as you said, this is now largely outside of the domain of the ROM itself.

Thank you for everything!
