### ISSUE TITLE
Shiny overworld pallete bug

### ISSUE THREAD

**Issue by XModxGodX** [resetes12/pokeemerald#4]
I got a shiny sandshrew in 1.4 and everything seemed fine however once it evolved the overworld sprite for sandslash became pink with green spines. Kind of a shame because shiny sandslash is one of my favorite shinies.

**Comment by resetes12** [comment]
The follower overworld sprite comes from HGSS and that's the color it has assigned to the body. Changing it means changing hundreds of follower sprites as they have the same colouration "issue" (the shadow colour is the primary colour in the follower overworld sprite, instead of the actual body colour) for consistency's sake.

I'm sorry but I don't think it's worth the time fixing. Anybody is free to do it though, and can request a pull request.
